Resources:
  OriginBucket:
    Type: AWS::S3::Bucket
    #    AWS CloudFormation keeps the resource without deleting it when its stack is deleted.
    DeletionPolicy: Retain
    Properties:
      BucketName: ${self:provider.environment.ORIGIN_BUCKET_NAME}
